### ISSUE TITLE
[edp-doctor]检查module id时忽略插件

### ISSUE THREAD

**Issue by otakustay** [ecomfe/edp#317]
我们这边在做一些独立package的时候，会去假设使用这个package的项目提供了`tpl!`或者`text!`等插件，而不会在package中放一个插件的实现，以避免多个类似的package加载了多个插件实例，导致相互数据隔离等很棘手的问题出现

在这种情况下，运行`edp doctor`是会报一些错误的：

```
edp INFO src/mvc/AccountCertifyDetailView.js
edp ERROR → No such module id: tpl!../tpl/accountCertifyDetail.tpl.html
edp INFO src/mvc/AccountFormView.js
edp ERROR → No such module id: tpl!../tpl/accountForm.tpl.html
edp INFO src/mvc/AccountInfoModel.js
```

我的一个想法是这样：

1. 可以在`.doctorrc`或者什么地方配置忽略一些插件，如`ignorePlugin: ['tpl', 'text']`
2. 遇到忽略的插件的时候，只检查`!`后面的relative id是否正确，反正如果插件重写了路径计算的规则，edp doctor也不会知道的

不知这样是否合理

**Comment by otakustay** [comment]
再补一点，是否也可以配置忽略一些包，如 https://github.com/ecomfe/edp/issues/315 所描述的，有些包并没有配在`package.json`中，最好检查时忽略掉

**Comment by leeight** [comment]
每个package都有package.json吧？把 ignorePlugin 放到 package.json 里面如何？比如：

```
edp: {
  doctor: {
    ignorePlugin: [....]
  }
}
```

**Comment by otakustay** [comment]
挺好，和fecs那边统一起来



Best regards

Gray Zhang



在 2015年1月14日 下午10:46:49, leeight (notifications@github.com) 写到:

view it on GitHub

**Comment by leeight** [comment]
> 挺好，和fecs那边统一起来

fecs支持从package.json里面读取配置么？不都是读取的.fecsrc么？

**Comment by otakustay** [comment]
有个issue好像在讨论统一到package.json

**Comment by leeight** [comment]
```json
{
  "edp": {
    "doctor": {
      "ignoreModules": [
        "zepto",
        "BMap",
        "*.tpl"
      ]
    }
  }
}
```

**Comment by leeight** [comment]
+ edp-doctor@1.0.8
