### ISSUE TITLE
[edp-package]edp import和update对本地包更新的逻辑不一致

### ISSUE THREAD

**Issue by otakustay** [ecomfe/edp#320]
使用`edp update`的话，本地有包要更新会先问一下是否更新，而`edp import`则二话不说直接给弄成最新的了

就我们现在的版本控制来说，弄成最新基本会死得惨惨的，所以`edp import`希望能够复用`update`的逻辑询问是否要更新

@leeight 这个问题能否较高优先级的支持一下，后续我们要去掉`dep`下的版本号，这会导致真更新上了回滚难度变高……

@Justineo 应该也关心这个问题

**Comment by leeight** [comment]
试试看
`npm i edp-package@beta`

**Comment by otakustay** [comment]
试了下，满足需要



Best regards

Gray Zhang



在 2015年2月5日 上午11:27:05, leeight (notifications@github.com) 写到:

试试看
npm i edp-package@beta
