### ISSUE TITLE
edp-build的ModuleCompiler合并时报依赖文件不是AMD模块错误

### ISSUE THREAD

**Issue by zwsf** [ecomfe/edp#325]
我使用react的jsx书写项目，在edp-build中构建了一个JSXTransformer处理器将jsx语法的文件转换为js语法文件。
JSXTransformer定义如下：

    var reactTools = require('react-tools');

    function defineJSXTransformer() {

        function JSXTransformer(opt) {
            AbstractProcessor.call(this, opt);
        }

        JSXTransformer.prototype = new AbstractProcessor();
        JSXTransformer.prototype.name = 'JSXTransformer';
        JSXTransformer.prototype.process = function (file, processContext, cb) {
            file.setData(reactTools.transform(file.data));
            cb && cb();
        }

        return JSXTransformer;
    }

jsxProcessor使用如下：

    var JSXTransformer = defineJSXTransformer();
    var jsxProcessor = new JSXTransformer({
        files: ['src/**/*.js']
    });

build时处理器顺序如下：

    stylusProcessor, cssProcessor, jsxProcessor, moduleProcessor, pathMapperProcessor

当build到模块合并时，入口文件的内容是从jsxProcessor处理器返回的，但其依赖文件是从文件中读取，导致认为所依赖模块不是AMD模块，没能正常进行模块的合并

**Comment by leeight** [comment]
是的，正在处理中，稍安勿躁

@otakustay

**Comment by zwsf** [comment]
好的~赞

**Comment by leeight** [comment]
@otakustay @PengXing @zwsf 试试最新的 `npm i -g edp-build@beta` 看看是否可以了

**Comment by leeight** [comment]
基本上把原来的实现重写了一次，不确定是否会不会引入新的问题，尽管UT都跑通过了

**Comment by leeight** [comment]
@PengXing 你要的那个功能的支持，我放到这里了，应该可以了吧？

https://github.com/ecomfe/edp-build/commit/0a1c0b4525486d63c44c9486138f0a89025ce57c#diff-4477a3a5faf066f408358f4487b82246R182

**Comment by PengXing** [comment]
亲测可用，辛苦

**Comment by zwsf** [comment]
反复安装了几次，只能安装到edp-build@1.0.15beta.7版本，测试amd合并还是不能通过，不知道是不是我的版本问题?

**Comment by leeight** [comment]
@zwsf 内网的镜像没同步，请采用官方的镜像即可安装：registry.npmjs.org

**Comment by zwsf** [comment]
ok了，辛苦~

**Comment by otakustay** [comment]
我这里build已经可以通过了，不过`ModuleCompiler`感觉比以往更慢了，不明白为啥不用读文件反而更慢……

**Comment by leeight** [comment]
是么，发个svn url够来瞅瞅看呗

**Comment by otakustay** [comment]
```sh
git clone http://gitlab.baidu.com/ssp/ssp.git
git co origin/es6-test
edp build -f
```

我这里大概用了1分钟多

```sh
edp INFO All done (67497ms)
```

基本上`ModuleCompiler`要500ms一个文件

**Comment by leeight** [comment]
目测没有 origin/es6-test 的分支，是不是忘记 push 了

**Comment by otakustay** [comment]
应该是有的，我本地还和remote是同步的……

```sh
~/Dev/ssp/ssp(branch:es6-test) » git br -a | grep es6
* es6-test
  remotes/origin/es6-test
```

是不是要`fetch --all`一下才行？

**Comment by leeight** [comment]
我用 master 分支看了看，貌似是因为我去掉了一个 Cache 导致的，主要的时间花费展开 `~esui` 这些定义的地方。基本上就是在遍历 processContext.files 的时候，检查每个 moduleId 是否满足 `edp.path.satisify`，我看看是不是可以把 Cache 再加回去。

因为大部分项目配置的要合并的文件不是特别多，不过对于你们的项目就有些特殊了，大量的需要合并的文件，所以这部分的花销就比较多了。

**Comment by leeight** [comment]
好像把 Cache 弄回去了也没有明显的改善，奇怪
