### ISSUE TITLE
[webserver]让babel支持source map

### ISSUE THREAD

**Issue by otakustay** [ecomfe/edp#331]
这东西没source map真难用

本来直接开`sourceMaps: "inline"`就行，但Chrome处理内联的source map有BUG……

所以我是这么想的：

1. `babel`收到请求，拿到请求的`url`除参数外的部分
2. 编译后在文件底下加`//# sourceMappingURL={url}.map`
3. 如果`babel`收到的请求是`.map`结尾的，去掉`.map`后找文件拿source map返回
4. 缓存可同时用于源文件和source map，因此请求`.js`和`.map`肯定只要编译一次（除非这中间文件变了算他倒霉）

**Comment by otakustay** [comment]
好像问题不是source map的事，我再看看……

**Comment by otakustay** [comment]
花了2小时没研究出来，无论怎么着sourcemap和源码在chrome的dev tool里也对应不上，这个 @firede 应该做`edp-test`的时候遇到过，应该有经验？

**Comment by firede** [comment]
`edp-test` @chriswong

**Comment by otakustay** [comment]
描述下问题：

1. 如果设置`sourceMaps: "inline"`会生成一个datauri形式的source map，但是在Chrome下，有些文件下断点会被跳到其它文件的源码里去
2. 如果设置`sourceMaps: true`并自己在文件结尾加上`sourceMapURL`，同时让babel对应请求返回source map json，则问题和上面一样
3. 我想可能是`filename`的问题，所以`transform`的时候加了`filename`选项，值就是当前请求的`pathname`，结果下断点的时候Chrome就不给我原ES6的代码了，同时断点位置会不一样，估计不能把`filename`设得一样
4. 我就想把`filename`换一换，结果换了还是没办法下断点……

**Comment by otakustay** [comment]
https://github.com/ecomfe/edp-webserver/pull/39

**Comment by leeight** [comment]
应该已经支持了吧
