### ISSUE TITLE
windows下edp build执行的最后出现一堆和git有关的报错

### ISSUE THREAD

**Issue by virola** [ecomfe/edp#333]
![edp-build](https://cloud.githubusercontent.com/assets/751800/8151856/e73278f4-1347-11e5-9887-44babe4f64ad.png)

如图， all done之后还去调了什么 `.git/config` ?

**Comment by leeight** [comment]
`edp -v`的输出结果看看？

或者安装最新的 edp-build 看看？ `npm i -g edp-build@beta`

**Comment by virola** [comment]
OK！安装了最新版的edp-build 之后好了。 Thanks!!~

顺附安装之前的edp版本：

edp -v
edp@1.1.1 C:\Users\virola\AppData\Roaming\npm\node_modules\edp
Builtin Commands:
  edp-config (1.0.2)
  edp-core (1.0.31)
  edp-beautify (0.1.1)
  edp-build (1.0.14)
  edp-minify (1.0.1)
  edp-package (0.5.6)
  edp-project (0.6.1)
  edp-watch (0.1.3)
  edp-webserver (1.0.16)

User Commands:
  edpx-add (1.0.3)
  edpx-mobile (1.0.0)
  edpx-ws (0.0.2)

**Comment by leeight** [comment]
看样子是 edp-build 的版本比较老了
